### ISSUE TITLE
Background-size support?

### ISSUE THREAD

**Issue by demiro** [Ensighten/grunt-spritesmith#101]
Hello,

I would like to use generated less in combination with background-size

lets say I have a sprite of 6 logos, that are divided in 3 columns per 2 rows. Original logo is 100x100px, so the sprite size would be 300x200px

now, each logo is normally 100x100px, but let's say I would like to have 60x60px size logos

normally I would use background-size: 60px 60px;

this option would be awesome

it would also be nice to provide already generated less examples... right now you are just using 2 samples in the comments

/*
The provided classes are intended to be used with the array-like variables

.icon-home {
  .sprite-width(@icon-home);
}
.icon-email {
  .sprite(@icon-email);
}
*/

would be nice to auto-generate all of them

**Comment by qbaty** [comment]
Add a option to handle background-size is really necessary
