### ISSUE TITLE
Multiple spritesheets foreach folder automatically

### ISSUE THREAD

**Issue by coyaniv** [Ensighten/grunt-spritesmith#106]
Can you add support for creating several sprites according to folder structure automatically?
e.g.
file structure:
images/
----- icons/
---------- a.png
---------- b.png
----- help/
---------- help1.png
---------- help2.png

srcDir = ../images

output files:
icons_sprite.png
help_sprite.png
icons_sprite.css
help_sprite.css

**Comment by twolfson** [comment]
This is a duplicate of #93. To elaborate on the closing comment of that issue, we try to keep `spritesmith` focused on doing one thing well; creating a spritesheet out of images. Other layers (e.g. `grunt`) handle generating multiple tasks with different inputs/outputs very well and we defer to their one thing well instead.
