### ISSUE TITLE
Provide an option to include/inject the css generated into existing stylesheets

### ISSUE THREAD

**Issue by HadrienPierart** [Ensighten/grunt-spritesmith#108]
Would be great if we could inject the generated CSS into existing stylesheet. This way, you can inject the declaration for a mobile spritesheet into à set of media queries for instance.
I have seen that in other grunt plugins, but I don't know if it's complicated...

Something like that :

**Comment by twolfson** [comment]
This can be done via a templating `grunt` task. I prefer to keep `spritesmith` focused on one thing well which is generating spritesheets instead of adding more features.

https://www.npmjs.com/package/grunt-templater

```js
sprite: {
  main: {
    destCss: 'output.css'
  }
},
template: {
  main: {
    variables: function () {
      return {
        spritesheetCss: grunt.file.read('output.css')
      };
    }
  }
}
```
