### ISSUE TITLE
Fatal error: tRNS for non-paletted images not yet supported.

### ISSUE THREAD

**Issue by bdelaney** [Ensighten/grunt-spritesmith#109]
Did initial setup per instructions. Threw a handful of .png files into my source folder. When running the Grunt task this is the error I received.

**Comment by twolfson** [comment]
I think that error message is the opposite of what it should be. It looks like you are using palette PNGs with transparency in them (case 3).

https://github.com/darkskyapp/pngparse/blob/def96c080ffc118cb35b10c1d5f35776e0343efe/index.js#L192-L194

http://www.w3.org/TR/PNG/#11tRNS

I don't have time to contribute that support to the PNG library. I am going to leave this issue open for now. Some options you have:

- Add support to `pngparse` (maintainer is very responsive)
    - https://github.com/darkskyapp/pngparse
- Convert your source images to a non-paletted PNG
    - See progressive format note in https://github.com/Ensighten/grunt-spritesmith/issues/80#issuecomment-67724081
- Use a different engine (e.g. `phantomjssmith`)

**Comment by bdelaney** [comment]
Wow, that was quick. Your reply in faster than my own troubleshooting.
I just finished changing the batch of pngs so they are non-transparent. The sprites now generate fine.
Thank You!
If I need transparency, I'll figure something else out and come back here to comment again.
But please feel free to close the issue.

**Comment by twolfson** [comment]
You don't need to ditch the transparency. It is the specific way that colors are being stored in your PNGs. If you load/save the PNGs via something like Photoshop, GIMP, or Pixlr, then the issue will likely go away and you can still keep transparency.

**Comment by bdelaney** [comment]
Great, I will try that.

**Comment by bdelaney** [comment]
Ah, thanks for that hint. Knowing very little about graphics files at this level, I went back to my utility of choice that I had originally processed the png files with, Irfanview (on Windows). By simply checking a box in the 'Save As' dialog, <Save Transparency as Alpha Channel>, it resolved the problem.
I also +1 your issue#10 on pngparse project.

**Comment by bdelaney** [comment]
Closing after using for a number of different scenarios and experiencing no issues.

**Comment by lukearmstrong** [comment]
I just managed to trigger this error after running [ImageOptim](https://imageoptim.com/) over my sprites folder, but because I have hundreds of sprites and the error message didn't tell me which file was causing the problem I can't really add anything of use to this issue other than "me too".

I usually just tend to run [ImageOptim](https://imageoptim.com/) over the resulting spritesheet files, as it knocks off a significant chunk, so I can still do that.
