### ISSUE TITLE
Provide option to generate SCSS map instead of plain variables

### ISSUE THREAD

**Issue by msikma** [Ensighten/grunt-spritesmith#113]
A brief explanation as to why I think this is useful to have.

One of the standard setups used for retina images is to have a filename suffix of `@2x` or `_2x` ([the latter of which is currently favored by Apple](https://developer.apple.com/library/safari/documentation/NetworkingInternet/Conceptual/SafariImageDeliveryBestPractices/ServingImagestoRetinaDisplays/ServingImagestoRetinaDisplays.html)) before the extension.

Currently, this can be set up by having two separate tasks for retina and regular: one that targets e.g. `'/**/*!(_2x).png'`, and one that targets `'/**/*_2x.png'`.

There's a problem, though. My goal is to make it so that I only have to write one single Sass function to set up a sprite for both regular and retina. But that's not possible since Spritesmith exports plain variables. Sass doesn't do variable variables, so I can't take an argument e.g. `my-sprite` from a function call and turn it into `my-sprite_2x` dynamically.

A map would solve this since it is possible to select a dynamic key.

**Comment by msikma** [comment]
Of course I could be missing something, maybe it is possible to do this in some way that I don't know about. If there is, it might be worth adding a note to the readme, I think this filename suffix setup is probably common enough.

**Comment by twolfson** [comment]
This has been covered at length in Ensighten/spritesmith#19. However, to answer your questions:

We provide maps via the `scss_maps` template:

https://github.com/twolfson/spritesheet-templates/tree/8.2.0#scss_maps

Each spritesheet's list of sprites can be found via `$spritesheet-sprites` (`scss` template). For multiple spritesheets, this variable name can be via `cssSpritesheetName`.

https://github.com/twolfson/spritesheet-templates/blob/8.2.0/lib/templates/scss.template.mustache#L35

https://github.com/Ensighten/grunt-spritesmith/tree/3.6.1

**Comment by msikma** [comment]
Thanks very much for the explanation :+1:

**Comment by twolfson** [comment]
We have added retina support in `grunt-spritesmith@4.5.0`. More information can be found here:

https://github.com/Ensighten/grunt-spritesmith#retina-parameters

https://github.com/Ensighten/grunt-spritesmith#retina-spritesheet

**Comment by msikma** [comment]
Thanks for the update, I've already set up a sort of hack myself—globbing _2x separately and writing some of my own mixins to be able to set up a sprite with the appropriate media queries. I suppose it's not worth sharing since we now have native support :)
