### ISSUE TITLE
Add spritesheetVarMap function

### ISSUE THREAD

**Issue by leevigraham** [Ensighten/grunt-spritesmith#116]
Similar to cssVarMap I think a spritesheetVarMap would be a nice option to have.

Use case:

Following the example here: https://github.com/hudochenkov/grunt-spritesmith-retina-mixins I'm creating a @2x sprite and a @1x sprite. The @1x sprite task is generating .scss from the template while the @2x task does not:

```javascript
/**
 * Converts icons into spritesheets
 */

var spriteIcons1x = paths.themesSrc + '/images/icons/*@1x.png';
var spriteIcons2x = paths.themesSrc + '/images/icons/*@2x.png';
var spritePadding = 50;

gulp.task('images:sprite:icons@1x', function () {
    var spriteData = gulp.src([spriteIcons1x])
        .pipe($.debug({title: 'spriteIcons1x:'}))
        .pipe($.spritesmith({
            imgName: 'images/icon-sprite@1x.png',
            imgPath: '../images/icon-sprite@1x.png',
            cssName: 'scss/screen/_icon_sprite.scss',
            padding: spritePadding,
            cssTemplate: paths.themesSrc + '/scss/spritesmith-retina-mixins.template.mustache',
            cssVarMap: function (sprite) {
                sprite.name = sprite.name.replace("@1x", "");
                sprite.image_2x = sprite.image.replace("@1x", "@2x");
                sprite.escaped_image_2x = sprite.image_2x.replace(/['"\(\)\s]/g, function encodeCssUri (chr) {
                    return '%' + chr.charCodeAt(0).toString(16);
                });;
            }
        }));
    spriteData.img.pipe(gulp.dest(paths.themesSrc));
    spriteData.css.pipe(gulp.dest(paths.themesSrc));
});

gulp.task('images:sprite:icons@2x', function () {
    var spriteData = gulp.src([spriteIcons2x])
        .pipe($.debug({title: 'spriteIcons2x:'}))
        .pipe($.spritesmith({
            imgName: 'images/icon-sprite@2x.png',
            imgPath: '../images/icon-sprite@2x.png',
            padding: spritePadding * 2,
            // This task filters out the sprite image
            // so the name cssName and cssTemplate don't matter
            // the template returns a blank string to speed up processing
            cssName: 'scss/screen/_sprites@2x.scss',
            cssTemplate: function(params){ return ''; }
            //cssTemplate: paths.themesSrc + '/scss/spritesmith-retina-mixins.template.mustache',
            //cssVarMap: function (sprite) {
            //    sprite.name = sprite.name.replace("@2x", "");
            //}
        }));

    return spriteData.img.pipe(gulp.dest(paths.themesSrc));
});

gulp.task('images:sprite:icons', ['images:sprite:icons@2x', 'images:sprite:icons@1x']);
```

In the `'images:sprite:icons@2x` task I'm returning an empty template (disabling template generation would also be welcome). 

In the `'images:sprite:icons@1x` task I'm rendering the .scss template and creating a new image_2x and escaped_image_2x value on the sprite object.

```javascript
cssVarMap: function (sprite) {
        sprite.name = sprite.name.replace("@1x", "");
        sprite.image_2x = sprite.image.replace("@1x", "@2x");
        sprite.escaped_image_2x = sprite.image_2x.replace(/['"\(\)\s]/g, function encodeCssUri (chr) {
            return '%' + chr.charCodeAt(0).toString(16);
        });;
}
```

This allows me to add those values into the .mustache template and then reference them without any of the [scss magic of the original post](https://github.com/hudochenkov/grunt-spritesmith-retina-mixins/blob/master/spritesmith-retina-mixins.template.mustache#L43):

```mustache
$sprite-map: (
	{{#items}}
	{{name}}: (
		offset-x: {{px.offset_x}},
		offset-y: {{px.offset_y}},
		width: {{px.width}},
		height: {{px.height}},
		image1x: '{{{escaped_image}}}',
		image2x: '{{{escaped_image_2x}}}'
	),
	{{/items}}
);

$spritesheet: (
  width: {{spritesheet.width}},
  height: {{spritesheet.height}},
  image1x: '{{spritesheet.image}}',
  // I would like to do this
  // image2x: '{{spritesheet.image_2x}}',
);

@mixin spritesheet-background-size($sprite) {
  background-size: map-get($spritesheet, 'width') map-get($spritesheet, 'height');
}

@mixin sprite-background-image-2x($sprite) {
  $sprite-data: map-get($sprite-map, $sprite);
  $sprite-path: map-get($sprite-data, 'image2x');
  background-image: url($sprite-path);
}

@mixin sprite-2x($sprite) {
  @media only screen and (-webkit-min-device-pixel-ratio: 2),
    only screen and (min--moz-device-pixel-ratio: 2),
    only screen and (-o-min-device-pixel-ratio: 2/1),
    only screen and (min-device-pixel-ratio: 2),
    only screen and (min-resolution: 192dpi),
    only screen and (min-resolution: 2dppx
  ) {
    @include spritesheet-background-size();
    @include sprite-background-image-2x($sprite);
  }
}
```

I'm currently using `{{spritesheet.width}}` to add global spritesheet properties to the mustache template in favour of using `total_height` and `total_width` which cleans things up.

So the the main part of the issue.

*I would like to be able to modify `{{spritesheet.image}}` and add  `{{spritesheet.image_2x}}` so I didn't have to pass a `$sprite` to `@mixin sprite-background-image-2x()` in a similar way to how I added `image_2x`*

**Comment by twolfson** [comment]
After reading a few times, I finally see what you are getting at. It looks like `cssVarMap` is being used for something it was never intended for. `cssVarMap` was built exclusively for naming of css variables but I guess you can do more with it.

I would like to take some time to think about this more. While the proposed strategy definitely works, it is more bending over backwards to make multiple sprite sizes work together. We should be using a wrapper that leverages the presented variables from multiple `spritesmith` runs (these could be wrapped by a single `grunt` task).

On a note for the meantime: `cssSpritesheetName` can be used to rename the retina spritesheet. Then, in the case of SASS 3.3, we could:

- Create another map which iterate over a set of sprites
- Save each sprite by its `name` to the map
- Walk over retina set and save 2x's to same sprite variable

But once again, this is a very limited scenario as SASS 3.3 is required.

**Comment by twolfson** [comment]
To give an ETA, I will post another thought by the end of the weekend (hopefully a resolution).

**Comment by leevigraham** [comment]
Thanks for taking a look. 

> After reading a few times, I finally see what you are getting at. It looks like cssVarMap is being used for something it was never intended for.

Yeah I'm using it to manipulate the template variables. I'm not sure of the best solution, just thought I would put down the use case.

Having the ability to modify the items and spritesheet in the grunt / gulp task would mean those modifications would be available to all templates.

**Comment by leevigraham** [comment]
I also realised I should have probably created this in https://github.com/Ensighten/spritesmith

**Comment by leevigraham** [comment]
Tweaking the .scss mustache template a little the same can be achieved with:

```scss
$spritesheet: (
  name: '{{spritesheet_name}}',
  width: {{spritesheet.px.width}},
  height: {{spritesheet.px.height}},
  image1x: '{{{spritesheet.image}}}',
  image2x: str-slice('{{{spritesheet.image}}}', 1, str-index('{{{spritesheet.image}}}', '@1x.png') - 1) + '@2x.png'
); 
```

Which removes the need for passing `$sprite` to `@mixin sprite-2x`.

Still this is template logic that probably should be avoided.

**Comment by twolfson** [comment]
I have come to the conclusion that this is a crutch that we should not be adding. Generating multiple spritesheets/variables from a single task should be approached as a separate problem than the current `grunt-spritesmith` task.

The interface will likely change (e.g. different `src`) as well as the templates. We can probably still leverage `spritesmith` under the hood. I am not sure when I will have time to approach that solution.

https://github.com/Ensighten/spritesmith/issues/19

For now I will leave this issue open.

**Comment by leevigraham** [comment]
Thanks for taking the time to take a look :)

**Comment by twolfson** [comment]
We have finally added retina support in `grunt-spritesmith@4.5.0`. More information can be found here:

https://github.com/Ensighten/grunt-spritesmith#retina-parameters

https://github.com/Ensighten/grunt-spritesmith#retina-spritesheet

**Comment by leevigraham** [comment]
Is this feature in https://github.com/Ensighten/spritesmith or just the grunt plugin? Any plans on adding this functionality to the gulp plugin?

**Comment by twolfson** [comment]
This has been added in `gulp.spritesmith@3.5.0` (also released yesterday). I have been thinking about moving the functionality into `spritesmith` but haven't decided yet.

**Comment by leevigraham** [comment]
:+1: for the gulp merge.
