### ISSUE TITLE
Fatal error: SOI not found

### ISSUE THREAD

**Issue by r670615769** [Ensighten/grunt-spritesmith#119]
have this problem   Fatal error: SOI not found

**Comment by r670615769** [comment]
maybe my picture have some problem

**Comment by twolfson** [comment]
Yep, this is likely a problem with your images. Can you try running your task with the images from the test suite?

https://raw.githubusercontent.com/Ensighten/grunt-spritesmith/4.2.0/src-test/test_files/sprite1.png

https://raw.githubusercontent.com/Ensighten/grunt-spritesmith/4.2.0/src-test/test_files/sprite2.jpg

**Comment by twolfson** [comment]
There has been no reply on this issue in 4 months. Closing this issue for now.
