### ISSUE TITLE
Hover class in first position in css

### ISSUE THREAD

**Issue by trompx** [Ensighten/grunt-spritesmith#120]
Hello, I try to create a sprite for 2 icons :
- favorite.png
- favorite-hover.png

No matter what I do, the css outputted always put the css for the favorite-hover.png at the beggining of the css file, thus overriden by the favorite css rules when hoverrig the dom element.

I tried to change the icon name for example 0favorite-hover.png believing that the name would change the order spritesmith process images but it doesn't seems to change anything.
Do you know if it is possible through a parameter or another way to specify some rules to put the hover css at the end of the file ?

Thank you very much for your help.

**Comment by trompx** [comment]
For people having the same problem : if you have the 2 files
favorite.png
favorite-hover.png
On windows, favorite.png appears before favorite-hover.png
But it seems that favorite-hover.png is processed before favorite.png

Renaming favorite-hover.png to z-favorite-hover.png solve the problem. It is processed before favorite.png and the css is placed at the end.

**Comment by twolfson** [comment]
This can also be resolved by forcing the order when passing the files into the `src`:

```js
src: ['favorite.png', 'favorite-hover.png']
```

There is sorting at the algorithm level that can be skipped. However, that should be irrelevant if the images are the same size.
