### ISSUE TITLE
Feature Request: Provide option to generate background-position in terms of percentage

### ISSUE THREAD

**Issue by abepark01** [Ensighten/grunt-spritesmith#121]
It would be great to be able to have option to use percentage values for the background-position, so that we can scale an image in a sprite.

Use case: I have a set of retina icons, but I want to display the icons at 50% using the background-size: 50% 50%.

Because the background-position is using fixed values (px) this doesn't work out.
Given that the offset_x and offset_y is available along with the total width and height are available as variables, perhaps a new mixin similar to @include sprite($sprite) would be awesome.

Any thoughts on this?

**Comment by twolfson** [comment]
Similar percentage based discussions have occurred in https://github.com/Ensighten/grunt-spritesmith/issues/84 and https://github.com/twolfson/gulp.spritesmith/issues/32 although they were about fluid sprites.

My main opposition is that percentage has a loss of precision at some point. For example, `1px/301px = 3.32225913...%`. This means at some point we need to truncate or the browser will truncate the sprite inaccurately.

If you are still interested in pushing forward with this, then you can define a template via the `cssTemplate` option. There are variables like `sprite.width` and `sprite.total_width` which should work fine for your purposes.
