### ISSUE TITLE
Any way to register a helper for the Handlebars template?

### ISSUE THREAD

**Issue by andreimoment** [Ensighten/grunt-spritesmith#123]
I'd like to do add a helper

    Handlebars.registerHelper('toLowerCase', function(str) {
      return str.toLowerCase();
    });
To use in my SCSS mustache template:

    {{#items}}
      .ts-{{toLowerCase name}} { background-position: sprite_position_percentage( {{px.offset_x}}, {{px.offset_y}} ) }
    {{/items}}

Where can I add such a helper?

**Comment by twolfson** [comment]
You can add the helper anywhere. Handlebars doesn't namespace helpers. That being said, there are simpler ways to adjust your variables. You can leverage `cssVarMap` to make the variables lower case:

```js
cssVarMap: function (sprite) {
  sprite.name = sprite.name.toLowerCase();
}
```

Alternatively, you can leverage our strings template variables and `variableNameTransforms`:

https://github.com/twolfson/spritesheet-templates#handlebars-template-data

```js
// Inside Gruntfile.js
// Convert all variable strings names to dash-case and lowercase
{cssOpts: {variableNameTransforms: ['dasherize', 'toLowerCase']}}
```

```
// Inside template
{{#items}}
  .ts-{{strings.name}} { background-position: sprite_position_percentage( {{px.offset_x}}, {{px.offset_y}} ) }
{{/items}}
```
