### ISSUE TITLE
Generating CSS only if neccessary

### ISSUE THREAD

**Issue by akoshman** [Ensighten/grunt-spritesmith#126]
Hello,

I want to ask a question — is there any way to prevent spritesmith generate CSS file?
If no, do you think there is any possible profit in speed of generating CSS in such case?

Thanks.

**Comment by twolfson** [comment]
Generating CSS is far from the limiting factor in this utility. Image manipulation is much more costly. Can you elaborate on when you would need the spritesheet without corresponding CSS?
