### ISSUE TITLE
minfication of CSS

### ISSUE THREAD

**Issue by bdelaney** [Ensighten/grunt-spritesmith#127]
I notice that in the Gulp project you document how to send the CSS stream for minification. Is this possible in the Grunt version, or an option for a template that I have not found.
No problem if not, can always minify as post-processing step in build.

**Comment by twolfson** [comment]
In `gulp.spritesmith`, the minification is done via a separate module. Both `grunt` and `gulp` build systems focus on tasks doing one thing well and chaining to perform higher level actions (e.g. building/minifying).

For the `grunt` integration, it's recommended to save to a separate temporary file and then generate the minified result from that. Then, we can register a task that does both:

```js
grunt.registerTask('sprite-and-minify', ['sprite', 'minify']);
```

This is one of the major complaints about `grunt`; there is no interim state to share between tasks.
