### ISSUE TITLE
Provide alternative SCSS output for libsass

### ISSUE THREAD

**Issue by qikkeronline** [Ensighten/grunt-spritesmith#128]
Hi there,

I switched to using libsass recently; but found that spritesmith outputted SCSS returns an error (as far as I can see it is due to missing features in libsass). Would it be possible to provide an alternative for libsass users untill libsass is completely compatible, or can I develop a template for this myself?

Kind regards (and thx for the awesome grunt plugin),

Gerben van Dijk

**Comment by twolfson** [comment]
We test against `libsass` in our templating library to verify support.

https://github.com/twolfson/spritesheet-templates/blob/9.4.0/test/scss_test.js#L42-L52

There is an existing issue for this on `gulp.spritesmith` about this. Can you follow the discussion there and contribute your `libsass` version and error message?

https://github.com/twolfson/gulp.spritesmith/issues/40
