### ISSUE TITLE
retina sprites and libsass

### ISSUE THREAD

**Issue by pasz** [Ensighten/grunt-spritesmith#129]
Hi,

I'm using spritesmith with libsass. I'm getting this error, every time I use the retina-sprite mixin:

Running "sass:dist" (sass) task
>>Running "sass:dist" (sass) task
>> index out of bounds for `nth($list, $n)`
>>   Line 2002  Column 18  src/sass/_sprites.scss
>>   Line 2002  Column 18  src/sass/_sprites.scss

Now I know it says that the sass task throws the error, so I thought it was a libsass problem.
The follow page says that libsass nth() didn't handle maps.

https://github.com/sass/libsass/issues/643

But, the page also says that the issue is resolved. I'm using the latest version of libsass so I'm thinking, maybe the problem lies with spritesmit?

**Comment by twolfson** [comment]
In the SCSS templates, we use `lists` with `nth` so that shouldn't be a problem. Can you paste your SCSS in a gist and how you are importing/using it? Also, what version of `libsass` are you using?

**Comment by pasz** [comment]
<script src="https://gist.github.com/pasz/f8628874c4aedc3af8d8.js"></script>

I'm using grunt-sass@0.18.1  and libsass version 3.1.0. From node_modules/grunt-sass/node_modules/node-sass :
{
  "name": "node-sass",
  "version": "2.1.1",
  "libsass": "3.1.0",
  "description": "Wrapper around libsass",
  "license": "MIT",
  "homepage": "https://github.com/sass/node-sass",
  "repository": {
    "type": "git",
    "url": "https://github.com/sass/node-sass"
  },

**Comment by twolfson** [comment]
@pasz You are using `retina-sprite` incorrectly. It should be used on a retina group not on the normal sprite. Additionally, the first `@include sprite` call is redundant to the `retina-sprite`.

```scss
h1:after {
	content: '';
	display: block;
	@include retina-sprite($bullet-check-group);
}
```
