### ISSUE TITLE
problem with numbers in file names

### ISSUE THREAD

**Issue by Leolik** [Ensighten/grunt-spritesmith#132]
This bug reproduced if I have images with index in filename more then 10 ((

For example, if icons count = 12 with names from icon1.png to icon12.png
```
>> Normal sprite has inconsistent size with retina sprite. "icon1" is 81x81 while "icon11@2x" is 112x90.
>> Normal sprite has inconsistent size with retina sprite. "icon12" is 56x45 while "icon1@2x" is 162x162.
```

**Comment by twolfson** [comment]
The `@` signs are messing with how `grunt` is reading in the order of the files. We have a few options:

# Manually specify file order over using globs
We can tell `grunt` to load files in a given order by not using a `glob`:

```js
src: ['icon1.png', 'icon2.png', ...]
```

# Move to zero-padded numbers
Our sort is being messed up due to `@` being considered lower than `1`/`2`. If we introduce zero padding to our file names then, we will avoid that issue (e.g. `0` will compare to `1` and `1` will compare to `1` for `01` and `11`).

```bash
mv icon1.png icon01.png
mv icon2.png icon02.png
mv icon3.png icon03.png
mv icon4.png icon04.png
mv icon5.png icon05.png
mv icon6.png icon06.png
mv icon7.png icon07.png
mv icon8.png icon08.png
mv icon9.png icon09.png
```

**Comment by toptalo** [comment]
Hello! maybe you can include some nat. sort module to fix this bug?

For example: https://www.npmjs.com/package/natural-compare-lite

**Comment by twolfson** [comment]
If we were to move to natural sorting, then sorting would inevitably break for someone else. It's best to keep it consistent/predictable with the rest of JS

**Comment by toptalo** [comment]
Howe can i fix it?
```
Normal sprite has inconsistent size with retina sprite.
"./img/sprite/menu-greendark-close.png" is 40x38 while
"./img/sprite/menu-greendark-close-small@2x.png" is 40x38.
```

**Comment by twolfson** [comment]
@toptalo The retina image (i.e. `@2x.png`) is expected to have twice as large dimensions (i.e. 80x76) but they are the same size.

**Comment by toptalo** [comment]
@twolfson, yes, but look to file names it different.
There a two files:
`menu-greendark-close.png` and `menu-greendark-close-small.png`
and two retina variants:
`menu-greendark-close@2x.png` and `menu-greendark-close-small@2x.png`

I think it will be better to serch just %fileneme%@2x file for retina, then just take next in order

**Comment by twolfson** [comment]
Ah, I missed that part. Can you file a separate issue? It's related but not the same as the original one on this thread.

**Comment by toptalo** [comment]
opened Issue #163 
Please help =)
