### ISSUE TITLE
Is it not compatible with newest stable node.js or io.js ?

### ISSUE THREAD

**Issue by Jsonzhang** [Ensighten/grunt-spritesmith#133]
It looks like only compatible with 0.10.* node version .

my environment is OSX Yosemite.

**Comment by twolfson** [comment]
We are testing against both `node@0.12` and `iojs` so they should work. What is the error you are seeing and can you copy/paste your `grunt config` for the `sprite` task?

https://github.com/Ensighten/grunt-spritesmith/blob/4.6.1/.travis.yml

**Comment by Jsonzhang** [comment]
after i switched my node version to node@0.12.4 . It shows error when i run it.

**Fatal error: Cannot define property:48, object is not extensible.**

my config for sprite as follow.

        sprite: {
                sprites: {
                    src: 'images/sprites/*.png',
                    destImg: 'images/sprites.png',
                    imgPath: '../images/sprites.png?'+ timestamp,
                    destCSS: 'less/mod/sprites.less',
                    cssFormat: 'css',
                    //cssTemplate: 'sprites.mustache',
                    cssOpts: {
                        cssClass: function(item) {
                            return '.' + item.name;
                        }
                    },
                    padding: 0
                },
                logo: {
                    src: 'images/logo/*.png',
                    destImg: 'images/logo.png',
                    imgPath: '../images/logo.png?'+ timestamp,
                    destCSS: 'less/mod/logo.less',
                    cssFormat: 'css',
                    //cssTemplate: 'sprites.mustache',
                    cssOpts: {
                        cssClass: function(item) {
                            return '.' + item.name;
                        }
                    },
                    padding: 0
                }
        },

ps:
i considered it is something wrong in installing. grunt-spritesmith i installed is `@1.24.0` .
Both installed  from npm again after delete and npm update command are'nt working. 
and the version of this plugin in github is 4.x.x now.

the registry of my npm config is  "http://registry.npmjs.org/"

**Comment by twolfson** [comment]
Yep, your config is very out of date. You need to account for the changed keys in `3.0.0`:

https://github.com/Ensighten/grunt-spritesmith/tree/4.7.1#breaking-changes-in-300

```js
    sprite: {
            sprites: {
                src: 'images/sprites/*.png',
                dest: 'images/sprites.png',
                imgPath: '../images/sprites.png?'+ timestamp,
                destCss: 'less/mod/sprites.less',
                cssFormat: 'css',
                //cssTemplate: 'sprites.mustache',
                cssOpts: {
                    cssSelector: function(item) {
                        return '.' + item.name;
                    }
                },
                padding: 0
            },
            logo: {
                src: 'images/logo/*.png',
                dest: 'images/logo.png',
                imgPath: '../images/logo.png?'+ timestamp,
                destCss: 'less/mod/logo.less',
                cssFormat: 'css',
                //cssTemplate: 'sprites.mustache',
                cssOpts: {
                    cssSelector: function(item) {
                        return '.' + item.name;
                    }
                },
                padding: 0
            }
    },
```

If things are still not working, then please paste the full error from `grunt sprite`.
