### ISSUE TITLE
How can I add Padding from the right and left

### ISSUE THREAD

**Issue by coyaniv** [Ensighten/grunt-spritesmith#134]
I want to create sprite with left and right padding
like: https://a2.muscache.com/airbnb/static/signinup/text-field-icons-9c18e4e23864cb33a8f0f7c32c0b86ee.png

How can I do it?

**Comment by twolfson** [comment]
Can you elaborate on your use case more? Why do you need the horizontal padding? Do you need the vertical padding between those icons as well or can they be collapsed to be almost touching each other vertically?

![text-field-icons-9c18e4e23864cb33a8f0f7c32c0b86ee](https://cloud.githubusercontent.com/assets/902488/7955510/7cbdcb2a-099e-11e5-98f0-f876a113e15c.png)

**Comment by coyaniv** [comment]
Both vertical and horizontal padding.  see image.
![capture](https://cloud.githubusercontent.com/assets/4752332/7955587/29e48fe4-09e2-11e5-94aa-08e7762d9c45.PNG)

**Comment by twolfson** [comment]
Can you elaborate on why you need the padding? When represented on the website, is the padding visible as well (e.g. it's part of the image)?

**Comment by coyaniv** [comment]
See Airbnb text field icons
https://www.airbnb.com/login

**Comment by twolfson** [comment]
Okay, in this scenario, the padding is part of the image itself. For example, if we were to not use a spritesheet (i.e. the image is standalone), then we would still have the whitespace padding as part of the image.

`spritesmith's` responsibility is to stitch images together into a spritesheet, not to add padding to generate said expected images. Our recommendations for this scenario is to:

- Use another `grunt` task to add your custom padding as needed
    - https://www.npmjs.com/package/grunt-gm
    - I believe the `gravity` and `extent` settings in their example are what you need
- Use a CLI tool (e.g. GraphicsMagick, ImageMagick) to automate this
    - http://graphicsmagick.org/
    - http://www.imagemagick.org/script/index.php

Then, once that piece is automated, pass in the generated images to `spritesmith` to get a spritesheet and CSS.
