### ISSUE TITLE
Option to add padding (to fix antialiasing) 

### ISSUE THREAD

**Issue by Strajk** [Ensighten/grunt-spritesmith#135]
First of all, thanks for awesome work!

I found a "bug", or maybe unwanted antialiasing feature when zooming webpage in Chrome

Example instead of 1000 words :)

Original sprite containing two images - blue and red square
![test](https://cloud.githubusercontent.com/assets/697301/8129866/f05f97cc-110d-11e5-803b-b9a0296ceb0b.png)

Rendering only green square
![a pen by pavel dolecek 2015-06-12 14-19-31](https://cloud.githubusercontent.com/assets/697301/8129883/22261902-110e-11e5-8791-2841a7cf9451.png)

Zooming Chrome to 75% produces leaking of the red square
![a pen by pavel dolecek 2015-06-12 14-20-26](https://cloud.githubusercontent.com/assets/697301/8129890/3754c1c0-110e-11e5-9140-e07a050c41ed.png)

Example to try in different browsers http://codepen.io/Strajk/pen/aOwREe

I believe that padding between images would fix this issue... or any other ideas?

**Comment by twolfson** [comment]
This is one of the first features we added to `spritesmith` :tada:

https://github.com/Ensighten/spritesmith/issues/7

There is a `padding` parameter for you to add which should solve this problem:

https://github.com/Ensighten/grunt-spritesmith/tree/4.7.1#documentation

```js
{
  // src, dest, destCss,
  padding: 1
}
```

**Comment by Strajk** [comment]
Everything is awesome :sparkles: , thanks!
