### ISSUE TITLE
It posible add ?v=xx preffix to generated css

### ISSUE THREAD

**Issue by Bogdaan** [Ensighten/grunt-spritesmith#143]
When i generate new sprite - old users fetch "icons.png" from local cache 
It posible generate version preffix to output background-image?

**Comment by twolfson** [comment]
The simplest way for a numeric based prefix would be to generate a timestamp as part of the filename:

```
dest: 'icons?v=' + Date.now() + '.png'
```

If you are interested in using an MD5 hash instead of a timestamp, please see #27
