### ISSUE TITLE
generate scss + css as result

### ISSUE THREAD

**Issue by Standa666** [Ensighten/grunt-spritesmith#144]
Is it possible to set that scss with mixins and variables and also css with classes will be generated?

I can only set only one of these formats, not both together.

**Comment by twolfson** [comment]
Can you explain your use case further? Why do you need both SCSS and CSS?

**Comment by Standa666** [comment]
Every file is intended to use by another group of people. One group cannot run transformation from scss into css so they require only css file. My group requires more sophisticated selectors for applying sprited pictures which can be handled via scss and @mixin only. My group requires scss only.

There might be the way forward in case of scss file contain also same classes as css file along with variables and @mixins.

**Comment by twolfson** [comment]
I am going to decline the request to add multiple output formats. `spritesmith` focuses on doing one thing well (generating spritesheets) and adding multiple outputs is going to add unnecessary complexity.

For your use case, I suggest generating SCSS and then as a follow-up task, generate CSS from that via the `@sprites` mixin (`@retina-sprites` if you are using retina spritesheets). This can be done via `grunt-contrib-sass` (Ruby SASS), `grunt-sass` (libsass/node-sass), or a CLI tool (e.g. Ruby SASS):

https://www.npmjs.com/package/grunt-contrib-sass

https://www.npmjs.com/package/grunt-sass
