### ISSUE TITLE
Set quality of return sprite

### ISSUE THREAD

**Issue by Shampoo1** [Ensighten/grunt-spritesmith#145]
How to set sprite quality, if I use ImageMagick engine and Grunt?

**Comment by twolfson** [comment]
The `gmsmith` engine accepts export options via `imgOpts`, these are passed directly to the engine:

https://github.com/Ensighten/grunt-spritesmith/tree/5.1.1#documentation

https://github.com/twolfson/gmsmith/tree/0.5.0#canvasexportoptions-cb

For your scenario, `quality` can be set via:

```
engine: 'gmsmith',
imgOpts: {
  quality: 75
}
```
