### ISSUE TITLE
Prevent sprite generation if no source images present

### ISSUE THREAD

**Issue by davetgreen** [Ensighten/grunt-spritesmith#147]
I've read the documentation and I can't see anything for this, so I thought I'd raise it as an issue. In our case, a modular boilerplate/framework we maintain uses spritesmith as part of the Grunt set-up. 

When it's used to create a new project it is incredibly likely that there will be no images at the source, meaning a 0 sized PNG will be created.

It would be great if spritesmith could not generate the PNG in this case. :+1: 

Not sure whether it's really relevant, but here is our spritesmith config:

```
module.exports = {
	all: {
		src: [
			'<%= siteInfo.assets_path %>/<%= siteInfo.img_dir %>/*.png',
			'!<%= siteInfo.assets_path %>/<%= siteInfo.img_dir %>/sprite.png'
		],
		dest: '<%= wpInfo.wp_content %>/themes/<%= wpInfo.theme_name %>/<%= wpInfo.img_dir %>/sprite.png',
		destCss: '<%= siteInfo.assets_path %>/<%= siteInfo.sass_dir %>/base/_sprites.scss',
		// Add a cache busting timestamp to the file name
		imgPath: '<%= wpInfo.assets_dir %>/<%= wpInfo.img_dir %>/sprite.png?' + ( new Date().getTime() ),
	}
};
```

**Comment by twolfson** [comment]
Unfortunately, this was a decision made early on. The reasoning is that we should provide consistent behavior for generating an image (even when nothing is provided). This seems to be consistent with canonical `grunt` plugins like `grunt-contrib-concat`.

https://github.com/gruntjs/grunt-contrib-concat

Could you explain why you don't want an image being created?

**Comment by davetgreen** [comment]
hey @twolfson

It's more of a housekeeping thing more than anything else to be honest. Thanks for the quick reply!
