### ISSUE TITLE
npm WARN package.json grunt-spritesmith@0.5.6 'repositories' (plural) Not supported.

### ISSUE THREAD

**Issue by select** [Ensighten/grunt-spritesmith#149]
I get this warning when I type `npm install` in a project that I inherited. Not sure if this is critical or not.

**Comment by twolfson** [comment]
You are on a very very old version of `grunt-spritesmith`. The current version is `5.1.8` and has a `repository` key:

https://github.com/Ensighten/grunt-spritesmith/blob/5.1.8/package.json#L37-L40

There are some major changes notes in the README:

https://github.com/Ensighten/grunt-spritesmith/tree/5.1.8#breaking-changes-in-300
