### ISSUE TITLE
No "sprite" targets found.

### ISSUE THREAD

**Issue by douglasdeodato** [Ensighten/grunt-spritesmith#150]
after run : grunt sprite, i got this.

all folders and files exists and are there, any help?

my grunt: 

/sprite min ===============================
				var spritesmith;
				config.spritesmith = spritesmith = {};			 
					
				  // Configure grunt
				  grunt.initConfig({
				    sprite:{
				      all: {
				        src: 'public/images/*.png',
				        dest: 'public/images/sprite/spritesheet.png',
				        destCss: 'sass/sprites.css'
				      }
				    }
				  });

**Comment by twolfson** [comment]
Can you paste your entire `Gruntfile.js` and the command you are running?

**Comment by douglasdeodato** [comment]
hi, thanks for your answer, that is my full gruntfile.js

https://gist.github.com/douglasdeodato/2137804a38ca1bc42f72

thank you.

**Comment by twolfson** [comment]
You are writing in too many layers of nesting for your config. Instead of `sprite.dist`, it should be `sprite.all` (or only `sprite.dist`):

```js
var sprite;
config.sprite = sprite = {};

// Configure grunt 
sprite.dist ={
  src: 'public/images/*.png',
  dest: 'public/images/sprite/spritesheet.png',
  destCss: 'sass/sprites.css'
};
```

**Comment by douglasdeodato** [comment]
thanks a lot, solved.

**Comment by kalburgimanjunath** [comment]
I am trying to generate svg its throwing an error,any help?

 sprite: {
            all: {
                src: 'assets/svg/*.svg',
                dest: 'assets/test.svg',
                destCss: 'assets/sprites.css'
            }
        }

Fatal error: Unsupported file type: image/svg+xml

**Comment by twolfson** [comment]
@kalburgimanjunath That is an unrelated error message/issue. `spritesmith` only supports bitmap images (e.g. `png`, `gif`, `jpg`) -- you'll likely want an SVG sprite library. If you have further questions, please open another issue
