### ISSUE TITLE
Fatal error: grunt.sprite requires a src, dest (img), and destCss property

### ISSUE THREAD

**Issue by douglasdeodato** [Ensighten/grunt-spritesmith#151]
i am getting this error after run grunt sprite

Fatal error: grunt.sprite requires a src, dest (img), and destCss property

//Sprite ===============================
		var sprite;
		config.sprite = sprite = {};
		
		  // Configure grunt 
		  sprite.dist ={
		    sprite:{
		      all: {
		         src: 'public/images/*.png',
				dest: 'public/images/sprite/spritesheet.png',
				destCss: 'sass/sprites.css'
		      }
		    }
		  };

**Comment by twolfson** [comment]
I have a feeling this is directly tied to #150. Closing this as a duplicate for now.

**Comment by douglasdeodato** [comment]
hi, thanks for your answer, that is my full gruntfile.js

https://gist.github.com/douglasdeodato/2137804a38ca1bc42f72

thank you.
