### ISSUE TITLE
Generated png

### ISSUE THREAD

**Issue by marocas** [Ensighten/grunt-spritesmith#152]
Hello, im trying to make a left-right png for some animation, my files are numbered from 00 to 29, and the output.png isn't coming like the expected.

Heres my sprite.js task.
´´´´
all: {
		//src: '<%= cfg.root %><%= cfg.src.images %>animation/anime_1/*.png',
		src: [
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/00.png',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/01.png',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/02.png',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/03.png',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/04.png',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/05.png',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/06.png',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/07.png',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/08.png',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/09.png',
			'...',
			'...',
			'...',
			'<%= cfg.root %><%= cfg.src.images %>animation/anime_1/29.png'
		],
		dest: '<%= cfg.root %><%= cfg.dest.images %>animation/animate.png',
		destCss: '<%= cfg.root %><%= cfg.src.images %>animation/animate.less',
		algorithm: 'left-right',
	},
´´´´
Am I missing something here??

this is the result
http://clientes.bycom.pt/00_Responsive_NL_Row_Tests/ByMailerTemplate/animations/animation/animate.png
and here are the sources: from 00.png to 29.png
http://clientes.bycom.pt/00_Responsive_NL_Row_Tests/ByMailerTemplate/animations/animation/00.png
http://clientes.bycom.pt/00_Responsive_NL_Row_Tests/ByMailerTemplate/animations/animation/**.png
http://clientes.bycom.pt/00_Responsive_NL_Row_Tests/ByMailerTemplate/animations/animation/29.png

**Comment by twolfson** [comment]
There is sorting which is enabled by default in our layout algorithms. While the images don't vary in size, JavaScript doesn't guarantee performing a stable sort. Can you try disabling sort in your configuration?

```js
{
  algorithm: 'left-right',
  algorithmOpts: {
    sort: false
  }
}
```

**Comment by marocas** [comment]
ohh!! i missed that, thanks you for your replay, its working.
Thank you once more :)
