### ISSUE TITLE
stylus and spritesmith

### ISSUE THREAD

**Issue by tutkun** [Ensighten/grunt-spritesmith#154]
Hi,
in the below i always auto-generating the _sprites@2x.styl file by grunt-spritesmith.
but, retina-images not yet exists. is it not bug?

MacBook-Pro:project myMac$ grunt stylus
Running "stylus:all" (stylus) task
>> ParseError: developer/stylus/modules/_sprites@2x.styl:17:24
>>    13| */
>>    14| $spritesheet_width = 0px;
>>    15| $spritesheet_height = 0px;
>>    16| $spritesheet_image = '../../sprites/search-icons@2x.png';
>>    17| $spritesheet_sprites =;
>> ------------------------------^
>>    18| $spritesheet = 0px 0px '../../sprites/search-icons@2x.png' $spritesheet_sprites;
>>    19| 
>>    20| /*
>> 
>> invalid right-hand side operand in assignment, got ";"
Warning: Stylus failed to compile. Use --force to continue.

**Comment by twolfson** [comment]
It looks like no images were found for your spritesheet. You can debug this via `--verbose`:

```bash
grunt sprite --verbose
```

**Comment by tutkun** [comment]
Hi twolfson, thanks. I know no images, but i want to if no images, spritesmith must be pass it. :)

**Comment by twolfson** [comment]
I don't understand your response. Could you rephrase it?
