### ISSUE TITLE
Fatal error: Invalid file signature

### ISSUE THREAD

**Issue by anthony-butcher** [Ensighten/grunt-spritesmith#158]
A very basic version isn't working

```
module.exports = function (grunt) {
  // Configure grunt
  grunt.initConfig({
    sprite:{
      all: {
        src: 'Sprites/*.png',
        dest: 'Sprites/output/test.png',
        destCss: 'Sprites/output/test.css'
      }
    }
  });

  // Load in `grunt-spritesmith`
  grunt.loadNpmTasks('grunt-spritesmith');
};
```

dependencies installed:
```
"devDependencies": {
    "grunt": "^0.4.5",
    "grunt-spritesmith": "^6.1.1"
  }
```

```
grunt sprite
Running "sprite:all" (sprite) task
Fatal error: Invalid file signature
```

**Comment by twolfson** [comment]
Can you upload the images you are using in `src`?

**Comment by anthony-butcher** [comment]
I managed to debug the task and found it was one image causing the error.  Once deleted it was fine - I will try re-saving the image.  Would be handy if the error message suggested the path of the bad image though.

**Comment by twolfson** [comment]
Glad to hear the problem has been resolved. Since the error is generated in `pngjs` it would prob be best to open an issue there to start outputting filepaths for images in errors (since error extension in JS isn't great).
