### ISSUE TITLE
[Question] HTML exemple output

### ISSUE THREAD

**Issue by marocas** [Ensighten/grunt-spritesmith#159]
By any chance you guys can make a html output with all icons with a caption of the variable used?

Best regards,
Mário Silva.

**Comment by twolfson** [comment]
As a quick answer, here's an example usage from our CSS template:

https://github.com/twolfson/spritesheet-templates/blob/10.0.0/lib/templates/css.template.handlebars#L2-L12

But you are right, we should provide an HTML example in our non-CSS templates. I will take a look at adding this by the end of next weekend.

**Comment by twolfson** [comment]
We have added HTML comments to `spritesheet-templates@10.1.0`, `grunt-spritesmith@6.3.0`, and `gulp.spritesmith@6.2.0`. Thanks for the issue =)

**Comment by marocas** [comment]
Thank you very much.
