### ISSUE TITLE
grunt-spritesmith keeps duplication the folder inside other

### ISSUE THREAD

**Issue by douglasdeodato** [Ensighten/grunt-spritesmith#162]
hi guys its a way for that task delete the older folder or just replace the images?

right now is creating a folder inside other like that:
images
  -min

if i run again the task creates other min inside the min
images
  -min
     -min

that is my config:

```
config.imagemin = imagemin = {};

					imagemin.dist = {
								  options: {
						          optimizationLevel: 5,
						          progressive: true,
						      },
						
					        files: [{
					            expand: true,
					            cwd: 'public/images/',
					            src: ['**/*.{png,jpg,gif}'],
					            dest: 'public/images/min'
					        }]
					 };
```

**Comment by twolfson** [comment]
This task (`grunt-spritesmith`) will replace the images by default. To delete the folder, we suggest using `grunt-contrib-clean`.

Outside of that, it sounds like you are describing/configuring `imagemin` which isn't this repo =/
