### ISSUE TITLE
wrong retina version for files with similar filenames

### ISSUE THREAD

**Issue by toptalo** [Ensighten/grunt-spritesmith#163]
I have several files with similar filenames such as:

```
menu-greendark-close.png
menu-greendark-close@2x.png
menu-greendark-close-small.png
menu-greendark-close-small@2x.png
```

Plugin return an error:
```
Normal sprite has inconsistent size with retina sprite. "./img/sprite/menu-greendark-close.png" is 40x38 while "./img/sprite/menu-greendark-close-small@2x.png" is 40x38.
```

**Comment by twolfson** [comment]
Can you add `gulp-debug` after `gulp.src` and tell us what the output is?

https://github.com/sindresorhus/gulp-debug

**Comment by toptalo** [comment]
hmm, how can i add gulp plugin to grunt?

**Comment by toptalo** [comment]
Sorry, it's my fall I missed some normal-size files!
Thanks!

**Comment by twolfson** [comment]
Glad to hear the issue got resolved =)
