### ISSUE TITLE
Automatically generate regular images from retina (@2x) ones?

### ISSUE THREAD

**Issue by silentbugs** [Ensighten/grunt-spritesmith#168]
Can spritesmith generate the simple images from the retina 2x ones that are provided? I tend to only have a retina version of an icon and would don't want to have to track all of my icons twice.

**Comment by twolfson** [comment]
For scenarios like this, we recommend using a secondary `grunt` task to generate the normal sized images. Here are some plugins which can help with that:

- https://www.npmjs.com/package/grunt-image-resize
- https://www.npmjs.com/package/grunt-imagemagick
- https://www.npmjs.com/package/grunt-gm

**Comment by silentbugs** [comment]
@twolfson thanks for the response. Would it make sense to write a backend for grunt-spritesmith that resizes images, or do you think it's better to have it outside of grunt-spritesmith?

**Comment by twolfson** [comment]
I'd prefer to keep them separate is practical for purposes outside of spritesmith. Someone could definitely wrap `spritesmith` with something that does resizing. However, that's more to maintain and a less frequent use case
