### ISSUE TITLE
Custom less variables with hdpi @2x images name

### ISSUE THREAD

**Issue by Orion98MC** [Ensighten/grunt-spritesmith#36]
Hi, I noticed that for .css format it's possible to alter the class names using cssOpts. However is it possible to do the same for the generated less @variables? I'm using hidpi images with "@2x" in their names which makes a lessc error.

Regards,
Thierry

**Comment by twolfson** [comment]
As a heads up, we have added retina support in `grunt-spritesmith@4.5.0`. More information can be found here:

https://github.com/Ensighten/grunt-spritesmith#retina-parameters

https://github.com/Ensighten/grunt-spritesmith#retina-spritesheet

**Comment by Orion98MC** [comment]
Great! Thanks for the heads up. Can't wait to use it in a future development.
