### ISSUE TITLE
Unsupported interlace method error.

### ISSUE THREAD

**Issue by AkshatAutomaton** [Ensighten/grunt-spritesmith#80]
When I run 'grunt sprite', I get following error:
Fatal error: Unsupported interlace method.

Does spritesmith depends on another tool, that I should install in order to make it work?

**Comment by julmot** [comment]
@twolfson Could you please explain how to use the workaround "phantomjssmith"?

**Comment by twolfson** [comment]
@julmot Sorry for the slow reply. A good example can be found in the README. For your purposes, you would swap `gmsmith` for `phantomjssmith`:

https://github.com/Ensighten/grunt-spritesmith/tree/5.0.0#engine

**Comment by twolfson** [comment]
Thanks to the efforts of @lukeapage we have changed the underlying PNG engine. The patch has been released in `grunt-spritesmith@5.1.0` and the issue should be resolved.
