### ISSUE TITLE
Responsive sprite images?

### ISSUE THREAD

**Issue by andrewboni** [Ensighten/grunt-spritesmith#84]
First of all, this is an awesome plugin. Really saves a lot of time and trouble.

I'm wondering- is there  a way to use `grunt-spritesmith` to force images to scale according to the width of its parent container?

Right now, it seems like all of the values that are generated are pixel values, not percentages, so they never change size. This is especially troublesome when used with Bootstrap 3's [`img-responsive` class](http://getbootstrap.com/css/#images), as images will get cut off on mobile (or any smaller screen).

HTML markup:

``` html
<div class="col-md-2 col-sm-6 col-xs-6">
    <a href="#">
        <div class="sprite1 img-responsive"></div>
    </a>
</div>
```

Generated stylus code via `grunt-spritesmith`:

``` stylus
$sprite1_x = 0px;
$sprite1_y = 0px;
$sprite1_offset_x = 0px;
$sprite1_offset_y = 0px;
$sprite1_width = 360px;
$sprite1_height = 240px;
$sprite1_total_width = 360px;
$sprite1_total_height = 1440px;
$sprite1_image = '../images/logos_sprite.png';
$sprite1 = 0px 0px 0px 0px 360px 240px 360px 1440px '../images/logos_sprite.png';
```

Result on smaller displays:
![screenshot 2014-05-31 15 02 08](https://cloud.githubusercontent.com/assets/255026/3140239/4c22aee6-e90f-11e3-9cb6-4014e7d0e040.png)

Any ideas on a solution? Thanks!

**Comment by denisz1** [comment]
Hey all [see a good approach here](https://github.com/twolfson/gulp.spritesmith/issues/32). Works well.
