### ISSUE TITLE
Fatal error: Image given has not completed loading

### ISSUE THREAD

**Issue by ttback** [Ensighten/grunt-spritesmith#92]
When running grunt-spritesmith, seeing an error  `Fatal error: Image given has not completed loading`
The verbose logs don't give enough info about what might be triggering this. 
the only hint found online is 
https://github.com/Automattic/node-canvas/issues/254
https://github.com/Automattic/node-canvas/issues/122

I don't know if you have any idea on what might trigger this.

**Comment by GuidoJansen** [comment]
I had this problem by copying Windows Thumbs.db file into the spritesmith directory.

**Comment by twolfson** [comment]
@GuidoJansen Can you verify that was with the `canvassmith` engine? If so, we should open a bug on the `node-canvas` repo.

https://github.com/Automattic/node-canvas
